name: Validate Integration

on:
  push:
    paths:
      - 'integration/**'
      - '.github/workflows/validate-integration.yml'
  pull_request:
    paths:
      - 'integration/**'
      - '.github/workflows/validate-integration.yml'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          path: "integration"
